# Generated by Django 3.2.4 on 2021-06-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='identification_number',
            field=models.CharField(max_length=255),
        ),
    ]
