# Generated by Django 3.2.4 on 2021-06-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsApi', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
