# Generated by Django 3.2.4 on 2021-06-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsApi', '0002_auto_20210617_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_banker',
            new_name='is_admin',
        ),
    ]
