# Generated by Django 3.2.4 on 2021-06-18 18:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsApi', '0002_auto_20210618_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='driving_license_picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='activation',
            name='identification_doc',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='activation',
            name='passport_photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
