# Generated by Django 3.2.4 on 2021-06-17 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsApi', '0003_rename_is_banker_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='analyticsApi.user')),
                ('is_valid', models.BooleanField(default=False)),
            ],
        ),
    ]
