# Generated by Django 3.2.4 on 2021-06-18 18:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsApi', '0004_auto_20210618_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='driving_license_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='driving_license'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
